### ISSUE TITLE
Offset images?

### ISSUE THREAD

**Issue by big-wisdom** [ragnarlotus/vue-flux#94]
Is there a way to offset individual images? I saw that you use a flux image component inside your the VueFlux component and that has an option for an offset. Is there a way for me to use this?

**Comment by ragnarlotus** [comment]
Hello, you can use those options when you use the component FluxImage independently, but not when using the VueFlux, because those are the options that use the slider to place the image properly.

As the dimensions of the window may change, the slider takes care of ensuring that the center of the image is always displayed and so is adapted and tries to cut as less as possible from the image.

Hope this answers your question.
